# Generated by Django 5.2.7 on 2025-10-28 17:44

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FrontendVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('video_url', cloudinary.models.CloudinaryField(max_length=255, verbose_name='video')),
            ],
        ),
        migrations.CreateModel(
            name='FrontendSourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_code', models.TextField(blank=True, null=True)),
                ('css_code', models.TextField(blank=True, null=True)),
                ('js_code', models.TextField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_codes', to='Tutorial.frontendvideo')),
            ],
        ),
        migrations.CreateModel(
            name='FrontendVideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='Tutorial.frontendvideo')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Tutorial.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, max_length=200, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='Tutorial.section')),
            ],
            options={
                'unique_together': {('section', 'name', 'icon_class')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Tutorial.language')),
            ],
            options={
                'unique_together': {('language', 'name')},
            },
        ),
        migrations.AddField(
            model_name='frontendvideo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Tutorial.topic'),
        ),
        migrations.CreateModel(
            name='BackendImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Tutorial.topic')),
            ],
        ),
        migrations.CreateModel(
            name='BackendStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_title', models.CharField(max_length=200)),
                ('step_description', models.TextField(blank=True, null=True)),
                ('step_source_code', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Tutorial.topic')),
            ],
            options={
                'verbose_name': 'Backend Step',
                'verbose_name_plural': 'Backend Steps',
                'ordering': ['step_number'],
                'unique_together': {('topic', 'step_number')},
            },
        ),
    ]
