# Generated by Django 5.2.7 on 2025-12-05 07:12

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Tutorial.category')),
            ],
            options={
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon_class', models.CharField(blank=True, max_length=200, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='Tutorial.section')),
            ],
            options={
                'unique_together': {('section', 'name', 'icon_class')},
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_info', models.TextField()),
                ('iframe_url', models.URLField()),
                ('download_repo_url', models.URLField(blank=True, null=True)),
                ('documentation', models.URLField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tutorial.templatetype')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Tutorial.language')),
            ],
            options={
                'unique_together': {('language', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FrontendSourceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled', max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_code', models.TextField(blank=True, null=True)),
                ('css_code', models.TextField(blank=True, null=True)),
                ('js_code', models.TextField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('hasBought', models.BooleanField(default=False)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_codes', to='Tutorial.topic')),
            ],
        ),
        migrations.CreateModel(
            name='BackendImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Tutorial.topic')),
            ],
        ),
        migrations.CreateModel(
            name='BackendStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('step_file_name', models.CharField(max_length=200)),
                ('step_description', models.TextField(blank=True, null=True)),
                ('step_source_code', models.TextField(blank=True, null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Tutorial.topic')),
            ],
            options={
                'verbose_name': 'Backend Step',
                'verbose_name_plural': 'Backend Steps',
                'ordering': ['step_number'],
                'unique_together': {('topic', 'step_number')},
            },
        ),
    ]
