# Generated by Django 5.2.7 on 2025-10-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backendstep',
            old_name='step_title',
            new_name='step_file_name',
        ),
        migrations.AlterField(
            model_name='frontendvideo',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
