# Generated by Django 5.2.7 on 2025-11-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0002_rename_step_title_backendstep_step_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsourcecode',
            name='access_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=10),
        ),
        migrations.AddField(
            model_name='frontendvideo',
            name='access_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=10),
        ),
    ]
