# Generated by Django 5.2.7 on 2025-12-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0002_frontendsourcecode_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template',
            old_name='documentation',
            new_name='documentation_url',
        ),
        migrations.AddField(
            model_name='template',
            name='github_repo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
