# Generated by Django 5.2.7 on 2025-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0003_rename_documentation_template_documentation_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cache Settings',
            },
        ),
    ]
