# Generated by Django 5.2.7 on 2025-11-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0004_sujan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sujan',
        ),
    ]
