# Generated by Django 5.2.7 on 2025-11-24 21:57

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0008_templatetype_template_template_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontendsourcecode',
            name='video',
        ),
        migrations.RemoveField(
            model_name='frontendvideoinfo',
            name='video',
        ),
        migrations.AddField(
            model_name='frontendsourcecode',
            name='hasBought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frontendsourcecode',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FrontendFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('video_url', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('access_type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], default='Free', max_length=10)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='Tutorial.topic')),
            ],
        ),
        migrations.AddField(
            model_name='frontendsourcecode',
            name='frame',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_codes', to='Tutorial.frontendframe'),
        ),
        migrations.CreateModel(
            name='FrontendFrameInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='Tutorial.frontendframe')),
            ],
        ),
        migrations.DeleteModel(
            name='FrontendVideo',
        ),
        migrations.DeleteModel(
            name='FrontendVideoInfo',
        ),
    ]
