# Generated by Django 5.2.7 on 2025-11-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0009_remove_frontendsourcecode_video_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='frontendframe',
            table='tutorial_frontendvideo',
        ),
        migrations.AlterModelTable(
            name='frontendframeinfo',
            table='tutorial_frontendvideoinfo',
        ),
    ]
