# Generated by Django 5.2.7 on 2025-11-25 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0010_alter_frontendframe_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontendframe',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='frontendsourcecode',
            name='frame',
        ),
        migrations.DeleteModel(
            name='FrontendFrameInfo',
        ),
        migrations.DeleteModel(
            name='FrontendFrame',
        ),
        migrations.DeleteModel(
            name='FrontendSourceCode',
        ),
    ]
