# Generated by Django 5.2.7 on 2025-11-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0012_frontendsourcecode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontendSourceCode',
        ),
    ]
