# Generated by Django 5.2.7 on 2025-12-03 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorial', '0016_clientprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientAuth',
        ),
    ]
