# Generated by Django 5.2.7 on 2025-12-08 15:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_emailotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='otp',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='otp_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
