# Generated by Django 5.2.7 on 2025-12-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0005_remove_emailotp_otp_emailotp_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_seed',
            field=models.CharField(blank=True, default='default', max_length=100),
        ),
    ]
